// RESONA DSP primitives (pure TypeScript, no Web Audio dependency).
export type Rng={next():number;uniform(a:number,b:number):number;gauss():number};
export function hashString(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
export function makeRng(seed:number):Rng{let a=seed|0,spare:number|null=null;const next=()=>{a=(a+0x6d2b79f5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296};return{next,uniform:(lo,hi)=>lo+(hi-lo)*next(),gauss:()=>{if(spare!==null){const s=spare;spare=null;return s}let u=0,v=0;while(u<=1e-12)u=next();v=next();const r=Math.sqrt(-2*Math.log(u));spare=r*Math.sin(2*Math.PI*v);return r*Math.cos(2*Math.PI*v)}}}
export function fft(re:Float64Array,im:Float64Array,inverse=false){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){let t=re[i];re[i]=re[j];re[j]=t;t=im[i];im[i]=im[j];im[j]=t}}for(let len=2;len<=n;len<<=1){const ang=((inverse?2:-2)*Math.PI)/len,wr0=Math.cos(ang),wi0=Math.sin(ang),half=len>>1;for(let i=0;i<n;i+=len){let wr=1,wi=0;for(let j=0;j<half;j++){const u=i+j,v=u+half,tr=re[v]*wr-im[v]*wi,ti=re[v]*wi+im[v]*wr;re[v]=re[u]-tr;im[v]=im[u]-ti;re[u]+=tr;im[u]+=ti;const nr=wr*wr0-wi*wi0;wi=wr*wi0+wi*wr0;wr=nr}}}if(inverse)for(let i=0;i<n;i++){re[i]/=n;im[i]/=n}}
const pow2=(n:number)=>{let p=1;while(p<n)p<<=1;return p};
export function convolve(a:Float64Array,b:Float64Array){const outLen=a.length+b.length-1,n=pow2(outLen),ar=new Float64Array(n),ai=new Float64Array(n),br=new Float64Array(n),bi=new Float64Array(n);ar.set(a);br.set(b);fft(ar,ai);fft(br,bi);for(let k=0;k<n;k++){const r=ar[k]*br[k]-ai[k]*bi[k];ai[k]=ar[k]*bi[k]+ai[k]*br[k];ar[k]=r}fft(ar,ai,true);return ar.slice(0,outLen)}
type C=[number,number];const cadd=(a:C,b:C):C=>[a[0]+b[0],a[1]+b[1]],csub=(a:C,b:C):C=>[a[0]-b[0],a[1]-b[1]],cmul=(a:C,b:C):C=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],cdiv=(a:C,b:C):C=>{const d=b[0]*b[0]+b[1]*b[1];return[(a[0]*b[0]+a[1]*b[1])/d,(a[1]*b[0]-a[0]*b[1])/d]},csqrt=(a:C):C=>{const r=Math.hypot(a[0],a[1]),re=Math.sqrt((r+a[0])/2),im=Math.sqrt(Math.max(0,(r-a[0])/2));return[re,a[1]<0?-im:im]};
export type Sos=[number,number,number,number,number];
export function butter(order:number,mode:'lowpass'|'highpass'|'bandpass',f1:number,sr:number,f2?:number):Sos[]{const N=Math.max(1,Math.min(8,Math.round(order))),fs2=2*sr,nyq=sr/2-1,warp=(f:number)=>fs2*Math.tan((Math.PI*Math.max(1,Math.min(nyq,f)))/sr),proto:C[]=[];for(let k=0;k<N;k++){const th=(Math.PI*(2*k+N+1))/(2*N);proto.push([Math.cos(th),Math.sin(th)])}let poles:C[]=[],zerosAtPlus=0,zerosAtMinus=0;if(mode==='lowpass'){const wc=warp(f1);poles=proto.map(p=>[p[0]*wc,p[1]*wc]);zerosAtMinus=N}else if(mode==='highpass'){const wc=warp(f1);poles=proto.map(p=>cdiv([wc,0],p));zerosAtPlus=N}else{const lo=warp(Math.min(f1,f2??f1*2)),hi=warp(Math.max(f1,f2??f1*2)),bw=hi-lo,w0sq=lo*hi;for(const p of proto){const h:C=[p[0]*bw/2,p[1]*bw/2],d=csqrt(csub(cmul(h,h),[w0sq,0]));poles.push(cadd(h,d),csub(h,d))}zerosAtPlus=N;zerosAtMinus=N}const zp=poles.map(p=>cdiv(cadd([fs2,0],p),csub([fs2,0],p))),upper=zp.filter(p=>p[1]>1e-9).sort((a,b)=>Math.hypot(a[0],a[1])-Math.hypot(b[0],b[1])),reals=zp.filter(p=>Math.abs(p[1])<=1e-9).map(p=>p[0]),sections:Sos[]=[];const takeZeros=(count:number):[number,number]=>{const zs:number[]=[];for(let i=0;i<count;i++){if(zerosAtPlus>0&&zerosAtPlus>=zerosAtMinus){zs.push(1);zerosAtPlus--}else if(zerosAtMinus>0){zs.push(-1);zerosAtMinus--}else if(zerosAtPlus>0){zs.push(1);zerosAtPlus--}}if(zs.length===1)return[-zs[0],0];if(zs.length===2)return[-(zs[0]+zs[1]),zs[0]*zs[1]];return[0,0]};for(const p of upper){const[b1,b2]=mode==='bandpass'?(()=>{zerosAtPlus--;zerosAtMinus--;return[0,-1]as[number,number]})():takeZeros(2);sections.push([1,b1,b2,-2*p[0],p[0]*p[0]+p[1]*p[1]])}for(let i=0;i<reals.length;i+=2){if(i+1<reals.length){const[b1,b2]=mode==='bandpass'?(()=>{zerosAtPlus--;zerosAtMinus--;return[0,-1]as[number,number]})():takeZeros(2);sections.push([1,b1,b2,-(reals[i]+reals[i+1]),reals[i]*reals[i+1]])}else{const[b1]=takeZeros(1);sections.push([1,b1,0,-reals[i],0])}}const ref=mode==='lowpass'?0:mode==='highpass'?Math.PI:2*Math.atan(Math.sqrt(warp(Math.min(f1,f2??f1*2))*warp(Math.max(f1,f2??f1*2)))/fs2),z:C=[Math.cos(ref),Math.sin(ref)],z2=cmul(z,z);let mag=1;for(const s of sections){const num=cadd(cadd([s[0]*z2[0],s[0]*z2[1]],[s[1]*z[0],s[1]*z[1]]),[s[2],0]),den=cadd(cadd(z2,[s[3]*z[0],s[3]*z[1]]),[s[4],0]);mag*=Math.hypot(...num)/Math.max(1e-30,Math.hypot(...den))}const g=1/Math.max(1e-30,mag);sections[0]=[sections[0][0]*g,sections[0][1]*g,sections[0][2]*g,sections[0][3],sections[0][4]];return sections}
export function sosfilt(sos:Sos[],x:Float64Array){const y=Float64Array.from(x);for(const[b0,b1,b2,a1,a2]of sos){let z1=0,z2=0;for(let i=0;i<y.length;i++){const xi=y[i],yi=b0*xi+z1;z1=b1*xi-a1*yi+z2;z2=b2*xi-a2*yi;y[i]=yi}}return y}
export function filter(x:Float64Array,mode:'lowpass'|'highpass'|'bandpass',f1:number,sr:number,order=2,f2?:number){return sosfilt(butter(order,mode,f1,sr,f2),x)}
export function sweepBandpass(x:Float64Array,sr:number,f0:number,f1:number,bw:number){const N=1024,hop=256,half=N/2,win=new Float64Array(N);for(let i=0;i<N;i++)win[i]=.5-.5*Math.cos(2*Math.PI*i/N);const padded=x.length+N,frames=Math.max(1,Math.ceil((padded-N)/hop)+1),total=(frames-1)*hop+N,src=new Float64Array(total);src.set(x,half);const out=new Float64Array(total),norm=new Float64Array(total),tLast=Math.max((frames-1)*hop/sr,1e-6),re=new Float64Array(N),im=new Float64Array(N),W=new Float64Array(half+1),lf0=Math.max(1,f0),lf1=Math.max(1,f1),sigma=Math.max(.05,bw);for(let fr=0;fr<frames;fr++){const o=fr*hop;for(let i=0;i<N;i++){re[i]=src[o+i]*win[i];im[i]=0}fft(re,im);const fc=lf0*Math.pow(lf1/lf0,(o/sr)/tLast);for(let k=0;k<=half;k++){const l=Math.log2((k*sr/N+1)/fc)/sigma;W[k]=Math.exp(-.5*l*l)}for(let k=0;k<N;k++){const w=W[k<=half?k:N-k];re[k]*=w;im[k]*=w}fft(re,im,true);for(let i=0;i<N;i++){out[o+i]+=re[i]*win[i];norm[o+i]+=win[i]*win[i]}}const y=new Float64Array(x.length);for(let i=0;i<x.length;i++){const n=norm[i+half];y[i]=n>1e-10?out[i+half]/n:0}return y}
export function hanning(L:number){const w=new Float64Array(L);if(L===1){w[0]=1;return w}for(let i=0;i<L;i++)w[i]=.5-.5*Math.cos(2*Math.PI*i/(L-1));return w}
export function mixInto(dst:Float64Array,src:Float64Array,offset:number,gain=1){const n=Math.min(src.length,dst.length-offset);for(let i=0;i<n;i++)dst[offset+i]+=src[i]*gain}
