// RESONA IR v3 deterministic renderer.
import type { Envelope, GrainsSource, ModalSource, Mode, Num, PluckSource, Processor, SoundProgram, Voice } from './ir.ts';
import { convolve, filter, hanning, hashString, makeRng, mixInto, sweepBandpass, type Rng } from './dsp.ts';
export const ENGINE_VERSION='RESONA DSP Engine v3.0';
type Ctx={sr:number;seed:number};
export function resolveNum(n:Num|undefined,rng:Rng,fallback:number){if(n===undefined||n===null)return fallback;if(typeof n==='number')return n;if('range'in n)return rng.uniform(n.range[0],n.range[1]);if('choice'in n&&n.choice.length)return n.choice[Math.floor(rng.next()*n.choice.length)%n.choice.length];return fallback}
export function nominal(n:Num|undefined,fallback=0){if(n===undefined||n===null)return fallback;if(typeof n==='number')return n;if('range'in n)return(n.range[0]+n.range[1])/2;if('choice'in n&&n.choice.length)return n.choice[0];return fallback}
const samples=(sec:number,sr:number)=>Math.max(1,Math.floor(sec*sr));
function expandModes(s:ModalSource){const out:Mode[]=[...(s.modes??[])];if(s.harmonics){const{count,rolloff,decay}=s.harmonics;for(let k=1;k<=Math.max(1,Math.min(64,Math.round(count)));k++)out.push({ratio:k,gain:1/Math.pow(k,rolloff),decay:decay??null})}return out}
function renderModal(s:ModalSource,d:number,ctx:Ctx,rng:Rng){const{sr}=ctx,L=samples(d,sr),y=new Float64Array(L),f0=resolveNum(s.freq,rng,440),pa=s.pitch?resolveNum(s.pitch.amount,rng,0):0,pd=s.pitch?Math.max(1e-4,resolveNum(s.pitch.decay,rng,.05)):1,gf=s.glide?resolveNum(s.glide.from,rng,1):1,gt=s.glide?Math.max(1e-4,resolveNum(s.glide.time,rng,.1)):1,vr=s.vibrato?resolveNum(s.vibrato.rate,rng,5):0,vd=s.vibrato?resolveNum(s.vibrato.depth,rng,0):0,vf=s.vibrato?Math.max(1e-4,resolveNum(s.vibrato.fadeIn,rng,.001)):1,modulated=!!(pa||s.glide||vd),ph=new Float64Array(L);if(modulated){let acc=0;for(let i=0;i<L;i++){const t=i/sr;let m=1+pa*Math.exp(-t/pd);if(s.glide)m*=gf+(1-gf)*Math.min(1,t/gt);if(vd)m*=1+vd*Math.sin(2*Math.PI*vr*t)*Math.min(1,t/vf);acc+=2*Math.PI*f0*m/sr;ph[i]=acc}}else for(let i=0;i<L;i++)ph[i]=2*Math.PI*f0*i/sr;const jit=s.jitter??0,gj=s.gainJitter??0,dj=s.decayJitter??0,randomPhase=s.randomPhase!==false;for(const m of expandModes(s)){const ratio=m.ratio*(1+rng.uniform(-jit,jit)),gain=m.gain*(1+rng.uniform(-gj,gj)),decay=m.decay==null?null:Math.max(1e-4,m.decay*(1+rng.uniform(-dj,dj))),phase=m.phase??(randomPhase?rng.uniform(0,2*Math.PI):0);if(ratio*f0>=sr/2)continue;const k=decay==null?1:Math.exp(-1/(sr*decay)),bloom=m.bloom&&m.bloom>0?m.bloom:0,kb=bloom?Math.exp(-1/(sr*bloom)):0;let e=1,b=1;for(let i=0;i<L;i++){y[i]+=gain*Math.sin(ph[i]*ratio+phase)*e*(bloom?1-b:1);e*=k;if(bloom)b*=kb}}const att=s.attack??.0005;if(att>0){const n=Math.min(L,Math.ceil(att*sr));for(let i=0;i<n;i++)y[i]*=Math.min(1,i/sr/att)}return y}
function renderPluck(s:PluckSource,d:number,ctx:Ctx,rng:Rng){const{sr}=ctx,L=samples(d,sr),f=Math.max(20,resolveNum(s.freq,rng,220)),damp=resolveNum(s.damping,rng,.996),bright=resolveNum(s.brightness,rng,.5),pick=resolveNum(s.pick,rng,.3),N=Math.max(2,Math.floor(sr/f));let buf:Float64Array=new Float64Array(N);for(let i=0;i<N;i++)buf[i]=rng.uniform(-1,1);if(bright<1)buf=new Float64Array(filter(buf,'lowpass',2000+bright*9000,sr,1));const k=Math.floor(N*pick);if(k>0){const src=buf.slice();for(let i=0;i<N;i++)buf[i]=src[i]-src[(i-k+N)%N]}const y=new Float64Array(L);let idx=0;for(let i=0;i<L;i++){const v=buf[idx],nx=buf[(idx+1)%N];buf[idx]=damp*.5*(v+nx);y[i]=v;idx=(idx+1)%N}const att=s.attack??.002;if(att>0){const n=Math.min(L,Math.ceil(att*sr));for(let i=0;i<n;i++)y[i]*=Math.min(1,i/sr/att)}return y}
function renderNoise(color:'white'|'uniform'|undefined,d:number,ctx:Ctx,rng:Rng){const L=samples(d,ctx.sr),y=new Float64Array(L);if(color==='uniform')for(let i=0;i<L;i++)y[i]=rng.uniform(-1,1);else for(let i=0;i<L;i++)y[i]=rng.gauss();return y}
function renderGrains(s:GrainsSource,d:number,ctx:Ctx,rng:Rng){const{sr}=ctx,L=samples(d,sr),y=new Float64Array(L),count=Math.floor(resolveNum(s.rate,rng,100)*d);for(let g=0;g<count;g++){const start=Math.floor(rng.uniform(0,d)*sr),len=Math.max(2,Math.floor(rng.uniform(s.grainDuration[0],s.grainDuration[1])*sr)),amp=rng.uniform(s.gain[0],s.gain[1]),w=hanning(len);let seg:Float64Array=new Float64Array(len);for(let i=0;i<len;i++)seg[i]=rng.gauss()*w[i]*amp;const fc=rng.uniform(s.freq[0],s.freq[1]);seg=new Float64Array(filter(seg,'bandpass',fc*.7,sr,1,Math.min(sr/2-100,fc*1.4)));mixInto(y,seg,start)}return y}
function applyEnvelope(x:Float64Array,e:Envelope,ctx:Ctx,rng:Rng){const{sr}=ctx,L=x.length;switch(e.type){case'exp':{const tau=Math.max(1e-4,resolveNum(e.decay,rng,.1)),att=resolveNum(e.attack,rng,.001),k=Math.exp(-1/(sr*tau));let v=1;for(let i=0;i<L;i++){x[i]*=v*(att>0?Math.min(1,i/sr/att):1);v*=k}break}case'window':{const p=resolveNum(e.power,rng,1);if(e.shape==='hann'){const w=hanning(L);for(let i=0;i<L;i++)x[i]*=Math.pow(w[i],p)}else for(let i=0;i<L;i++)x[i]*=Math.pow(Math.max(0,Math.sin(Math.PI*i/Math.max(1,L-1))),p);break}case'gauss':{const c=resolveNum(e.center,rng,.05),w=Math.max(1e-4,resolveNum(e.width,rng,.05));for(let i=0;i<L;i++){const u=(i/sr-c)/w;x[i]*=Math.exp(-u*u)}break}case'ar':{const a=Math.max(1e-4,resolveNum(e.attack,rng,.01)),r=Math.max(1e-4,resolveNum(e.release,rng,.1)),d=L/sr;for(let i=0;i<L;i++){const t=i/sr;x[i]*=Math.max(0,Math.min(1,t/a,(d-t)/r))}break}case'tailFade':{const n=Math.max(1,Math.floor(L*Math.max(0,Math.min(1,resolveNum(e.fraction,rng,.25)))));for(let i=0;i<n;i++)x[L-n+i]*=.5*(1+Math.cos(Math.PI*i/Math.max(1,n-1)));break}}}
function room(x:Float64Array,size:number,wet:number,bright:number,pre:number,ctx:Ctx,rng:Rng){const{sr}=ctx,n=samples(size,sr);let ir:Float64Array=new Float64Array(n);const tau=size/5.5;for(let i=0;i<n;i++)ir[i]=rng.gauss()*Math.exp(-i/sr/tau);ir=new Float64Array(filter(ir,'lowpass',bright,sr,1));const p=Math.floor(sr*pre),full=new Float64Array(p+n);full.set(ir,p);let energy=0;for(let i=0;i<full.length;i++)energy+=full[i]*full[i];const g=1/Math.sqrt(Math.max(1e-20,energy));for(let i=0;i<full.length;i++)full[i]*=g;const w=convolve(x,full),out=new Float64Array(w.length);for(let i=0;i<w.length;i++)out[i]=(i<x.length?x[i]*(1-wet):0)+w[i]*wet*1.6;return out}
function processChain(x:Float64Array,chain:Processor[]|undefined,ctx:Ctx,rng:Rng){let y:Float64Array=x;for(const p of chain??[])y=new Float64Array(processOne(y,p,ctx,rng));return y}
function processOne(x:Float64Array,p:Processor,ctx:Ctx,rng:Rng):Float64Array{const{sr}=ctx;switch(p.type){case'filter':{const f=resolveNum(p.freq,rng,1000),order=p.order??2;return p.mode==='bandpass'?filter(x,'bandpass',f,sr,order,resolveNum(p.freq2,rng,f*2)):filter(x,p.mode,f,sr,order)}case'sweep':return sweepBandpass(x,sr,resolveNum(p.from,rng,500),resolveNum(p.to,rng,2000),resolveNum(p.bandwidth,rng,1));case'envelope':{const y=Float64Array.from(x);applyEnvelope(y,p.envelope,ctx,rng);return y}case'gain':{const g=resolveNum(p.value,rng,1);return new Float64Array(Array.from(x,v=>v*g))}case'saturate':{const k=Math.max(.01,resolveNum(p.drive,rng,1)),n=Math.tanh(k);return new Float64Array(Array.from(x,v=>Math.tanh(k*v)/n))}case'randomAM':{const floor=resolveNum(p.floor,rng,.3),rate=Math.max(.1,resolveNum(p.rate,rng,6)),r=new Float64Array(x.length);for(let i=0;i<r.length;i++)r[i]=Math.abs(rng.gauss());const am=filter(r,'lowpass',rate,sr,1);let mx=1e-12;for(const v of am)mx=Math.max(mx,v);return new Float64Array(Array.from(x,(v,i)=>v*(floor+am[i]/mx)))}case'parallel':{const outs=p.branches.map(b=>{const g=resolveNum(b.gain,rng,1);return new Float64Array(Array.from(processChain(Float64Array.from(x),b.processors,ctx,rng),v=>v*g))}),y=new Float64Array(Math.max(x.length,...outs.map(o=>o.length)));for(const o of outs)mixInto(y,o,0);return y}case'room':return room(x,Math.max(.05,resolveNum(p.size,rng,.6)),Math.max(0,Math.min(1,resolveNum(p.wet,rng,.18))),resolveNum(p.brightness,rng,4000),Math.max(0,resolveNum(p.preDelay,rng,.012)),ctx,rng)}}
function voiceRng(ctx:Ctx,path:string){return makeRng(hashString(ctx.seed+':'+path))}
type Rendered={data:Float64Array;offset:number};
function renderVoice(v:Voice,ctx:Ctx,path:string,inherited?:number):Rendered|null{if(v.mute)return null;const rng=voiceRng(ctx,path),at=Math.max(0,resolveNum(v.at,rng,0)),gain=resolveNum(v.gain,rng,1),d=Math.max(.001,v.duration!==undefined?resolveNum(v.duration,rng,.5):inherited??.5),s=v.source;let x:Float64Array;if(s.type==='group')x=mixVoices(s.voices,ctx,path,v.duration!==undefined?d:inherited);else if(s.type==='modal')x=renderModal(s,d,ctx,rng);else if(s.type==='pluck')x=renderPluck(s,d,ctx,rng);else if(s.type==='grains')x=renderGrains(s,d,ctx,rng);else x=renderNoise(s.color,d,ctx,rng);for(const e of v.envelope??[])applyEnvelope(x,e,ctx,rng);x=processChain(x,v.processors,ctx,rng);if(gain!==1)for(let i=0;i<x.length;i++)x[i]*=gain;return{data:x,offset:Math.floor(at*ctx.sr)}}
function mixVoices(voices:Voice[],ctx:Ctx,path:string,inherited?:number){const parts=voices.map((v,i)=>renderVoice(v,ctx,path+'/'+i+':'+v.id,inherited)).filter((r):r is Rendered=>!!r),len=Math.max(1,...parts.map(p=>p.offset+p.data.length)),y=new Float64Array(len);for(const p of parts)mixInto(y,p.data,p.offset);return y}
export type RenderOptions={variant?:number;sampleRate?:number;solo?:number;normGain?:number};export type RenderResult={data:Float32Array;sampleRate:number;duration:number;normGain:number;seed:number};
export function renderProgram(p:SoundProgram,opts:RenderOptions={}):RenderResult{const sr=opts.sampleRate??p.sampleRate??48000,seed=(p.seed|0)+(opts.variant??0),ctx:Ctx={sr,seed},voices=opts.solo===undefined?p.voices:p.voices.map((v,i)=>i===opts.solo?v:{...v,mute:true});let x:Float64Array=mixVoices(voices,ctx,'root');x=processChain(x,p.processors,ctx,voiceRng(ctx,'master'));const m=p.master??{};if(m.dcRemove!==false){let mean=0;for(const v of x)mean+=v;mean/=x.length;for(let i=0;i<x.length;i++)x[i]-=mean}let normGain=1;if(opts.normGain!==undefined)normGain=opts.normGain;else if(m.normalize!==null&&m.normalize!==undefined){let peak=1e-9;for(const v of x)peak=Math.max(peak,Math.abs(v));normGain=Math.pow(10,m.normalize/20)/peak}const g=normGain*(m.gain??1);let end=x.length,trim=m.trimDb===undefined?-80:m.trimDb;if(trim!==null){const thr=Math.pow(10,trim/20);let last=0;for(let i=x.length-1;i>=0;i--)if(Math.abs(x[i]*g)>thr){last=i;break}end=Math.min(x.length,last+Math.floor(.02*sr)+1)}const out=new Float32Array(end);for(let i=0;i<end;i++)out[i]=x[i]*g;const fade=Math.min(end,Math.floor(((m.fadeOutMs??8)/1000)*sr));for(let i=0;i<fade;i++)out[end-fade+i]*=1-i/Math.max(1,fade-1);return{data:out,sampleRate:sr,duration:end/sr,normGain,seed}}
export function estimateDuration(p:SoundProgram){const roomTail=(chain?:Processor[]):number=>(chain??[]).reduce((s,x)=>s+(x.type==='room'?nominal(x.size,.6)+nominal(x.preDelay,.012):x.type==='parallel'?Math.max(0,...x.branches.map(b=>roomTail(b.processors))):0),0),voiceLen=(v:Voice,inh:number):number=>{if(v.mute)return 0;const d=v.duration!==undefined?nominal(v.duration,.5):inh;return nominal(v.at,0)+(v.source.type==='group'?Math.max(0,...v.source.voices.map(c=>voiceLen(c,d))):d)+roomTail(v.processors)};return Math.max(.05,...p.voices.map(v=>voiceLen(v,.5)))+roomTail(p.processors)}
export function encodeWav(data:Float32Array,sr:number){const ds=data.length*2,ab=new ArrayBuffer(44+ds),v=new DataView(ab),w=(o:number,s:string)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+ds,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,ds,true);for(let i=0;i<data.length;i++){const s=Math.max(-1,Math.min(1,data[i]));v.setInt16(44+i*2,s<0?s*32768:s*32767,true)}return new Uint8Array(ab)}
