export type Waveform='sine'|'square'|'sawtooth'|'triangle'|'noise';
export type Layer={id:string;waveform:Waveform;frequency:number;detune:number;gain:number;pitchDrop:number;filterFrequency?:number;filterQ?:number;fmAmount?:number;fmRatio?:number};
export type SoundDefinition={version:1;seed:number;name:string;duration:number;attack:number;decay:number;sustain:number;release:number;filterFrequency:number;filterQ:number;distortion:number;delay:number;masterGain:number;limiter:boolean;layers:Layer[]};
export const defaultSound:SoundDefinition={version:1,seed:777,name:'Neon Confirm',duration:.85,attack:.01,decay:.18,sustain:.42,release:.3,filterFrequency:3200,filterQ:4,distortion:6,delay:.12,masterGain:.82,limiter:true,layers:[{id:'tone',waveform:'sawtooth',frequency:440,detune:0,gain:.2,pitchDrop:0,filterFrequency:7000,filterQ:1,fmAmount:0,fmRatio:2},{id:'shine',waveform:'sine',frequency:880,detune:7,gain:.1,pitchDrop:240,filterFrequency:9000,filterQ:1,fmAmount:35,fmRatio:2}]};
function rng(seed:number){let a=seed|0;return()=>{a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296}}function hash(s:string){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
function env(g:AudioParam,s:number,d:SoundDefinition,peak:number){const end=s+Math.max(.01,d.duration),a=Math.min(end-.003,s+Math.max(.001,Math.min(d.attack,d.duration*.45))),de=Math.max(a+.001,Math.min(end-.002,a+Math.max(.001,d.decay))),su=Math.max(de,Math.min(end-.001,end-Math.max(.001,d.release)));g.setValueAtTime(.0001,s);g.exponentialRampToValueAtTime(Math.max(.0001,peak),a);g.exponentialRampToValueAtTime(Math.max(.0001,peak*d.sustain),de);g.setValueAtTime(Math.max(.0001,peak*d.sustain),su);g.exponentialRampToValueAtTime(.0001,end)}
function noise(ctx:BaseAudioContext,n:number,seed:number){const b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*n),ctx.sampleRate),x=b.getChannelData(0),r=rng(seed);for(let i=0;i<x.length;i++)x[i]=r()*2-1;return b}
function curve(amount:number){const n=1024,c=new Float32Array(n),k=amount*8;for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=(1+k)*x/(1+k*Math.abs(x))}return c}
function graph(ctx:BaseAudioContext,d:SoundDefinition,dest:AudioNode,start:number){const mix=ctx.createGain(),f=ctx.createBiquadFilter(),sh=ctx.createWaveShaper(),dry=ctx.createGain(),wet=ctx.createGain(),del=ctx.createDelay(1),master=ctx.createGain(),lim=ctx.createDynamicsCompressor();f.type='lowpass';f.frequency.value=d.filterFrequency;f.Q.value=d.filterQ;sh.curve=curve(d.distortion);sh.oversample='2x';dry.gain.value=1;wet.gain.value=Math.min(.65,d.delay);del.delayTime.value=.16;master.gain.value=d.masterGain??1;lim.threshold.value=-1;lim.knee.value=0;lim.ratio.value=20;lim.attack.value=.003;lim.release.value=.08;mix.connect(f);f.connect(sh);sh.connect(dry);sh.connect(del);del.connect(wet);dry.connect(master);wet.connect(master);if(d.limiter!==false){master.connect(lim);lim.connect(dest)}else master.connect(dest);for(const l of d.layers){const a=ctx.createGain(),lf=ctx.createBiquadFilter();lf.type='lowpass';lf.frequency.value=l.filterFrequency??18000;lf.Q.value=l.filterQ??.7;env(a.gain,start,d,l.gain);a.connect(lf);lf.connect(mix);if(l.waveform==='noise'){const s=ctx.createBufferSource();s.buffer=noise(ctx,d.duration+.05,(d.seed^hash(l.id))>>>0);s.connect(a);s.start(start);s.stop(start+d.duration+.03)}else{const o=ctx.createOscillator();o.type=l.waveform;o.detune.value=l.detune;o.frequency.setValueAtTime(Math.max(20,l.frequency),start);if(l.pitchDrop)o.frequency.exponentialRampToValueAtTime(Math.max(20,l.frequency-l.pitchDrop),start+d.duration);if((l.fmAmount??0)>0){const mod=ctx.createOscillator(),mg=ctx.createGain();mod.frequency.value=Math.max(1,l.frequency*(l.fmRatio??2));mg.gain.value=l.fmAmount??0;mod.connect(mg);mg.connect(o.frequency);mod.start(start);mod.stop(start+d.duration+.03)}o.connect(a);o.start(start);o.stop(start+d.duration+.03)}}}
export function playSound(ctx:AudioContext,d:SoundDefinition){const bus=ctx.createGain();bus.connect(ctx.destination);graph(ctx,d,bus,ctx.currentTime);return()=>{try{bus.gain.cancelScheduledValues(ctx.currentTime);bus.gain.setValueAtTime(bus.gain.value,ctx.currentTime);bus.gain.linearRampToValueAtTime(0,ctx.currentTime+.015);setTimeout(()=>bus.disconnect(),30)}catch{bus.disconnect()}}}
export async function renderSound(d:SoundDefinition){const sr=48000,c=new OfflineAudioContext(1,Math.ceil(sr*(d.duration+.35)),sr);graph(c,d,c.destination,0);return c.startRendering()}
function ascii(v:DataView,o:number,s:string){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))}export function audioBufferToWav(b:AudioBuffer){const c=b.numberOfChannels,sr=b.sampleRate,f=b.length,ba=c*2,ds=f*ba,ab=new ArrayBuffer(44+ds),v=new DataView(ab);ascii(v,0,'RIFF');v.setUint32(4,36+ds,true);ascii(v,8,'WAVE');ascii(v,12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,c,true);v.setUint32(24,sr,true);v.setUint32(28,sr*ba,true);v.setUint16(32,ba,true);v.setUint16(34,16,true);ascii(v,36,'data');v.setUint32(40,ds,true);let o=44;for(let i=0;i<f;i++)for(let ch=0;ch<c;ch++){const s=Math.max(-1,Math.min(1,b.getChannelData(ch)[i]));v.setInt16(o,s<0?s*32768:s*32767,true);o+=2}return new Blob([ab],{type:'audio/wav'})}
export async function exportWav(d:SoundDefinition){const b=await renderSound(d),u=URL.createObjectURL(audioBufferToWav(b)),a=document.createElement('a');a.href=u;a.download=(d.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'resona')+'.wav';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
