import{renderSound,type SoundDefinition}from'./audio';import{inspectBuffer,type AudioMetrics}from'./inspector';import{spectrogram}from'./spectrogram';import{attributeLayers,surgicalFix}from'./attribution';import{fixSound}from'./autofix';
export type RepairIssue='level'|'high-frequency'|'sub-bass'|'dc';
export type OptimizeStep={iteration:number;issue:RepairIssue;action:string;before:AudioMetrics;after:AudioMetrics;target:string|null};
export type OptimizeResult={value:SoundDefinition;steps:OptimizeStep[];verified:boolean;stopReason:string};
const ok=(m:AudioMetrics)=>m.status==='clean';
function issue(m:AudioMetrics):RepairIssue|null{if(m.clipped||m.peak>.95||m.rms>.5)return'level';if(Math.abs(m.dc)>.01)return'dc';if(m.lowRatio>.35)return'sub-bass';if(m.highRatio>.22)return'high-frequency';return null}
export async function optimizeSound(input:SoundDefinition,max=4,signal?:AbortSignal):Promise<OptimizeResult>{const alive=()=>{if(signal?.aborted)throw new DOMException('Optimization cancelled','AbortError')};alive();const limit=Math.max(1,Math.min(8,Math.floor(max)||1));let value=input,buffer=await renderSound(value);alive();let before=inspectBuffer(buffer);const steps:OptimizeStep[]=[];if(ok(before))return{value,steps,verified:true,stopReason:'Already clean by Inspector rules'};for(let i=1;i<=limit;i++){alive();const problem=issue(before);if(!problem)return{value,steps,verified:ok(before),stopReason:'No recognized repair issue'};let action='',target:string|null=null,next=value;if(problem==='level'){const r=fixSound(value,before);next=r.value;action='Master gain correction x '+r.report.gainScale.toFixed(3)}else if(problem==='high-frequency'){const sp=spectrogram(buffer),a=await attributeLayers(value,sp.bursts);alive();const r=surgicalFix(value,a);next=r.value;target=r.target;action=r.action}else if(problem==='sub-bass'){const hz=Math.min(24000,Math.max(140,Math.round(value.filterFrequency*1.08)));return{value,steps,verified:false,stopReason:'Sub-bass anomaly requires a high-pass stage; low-pass cutoff '+hz+' Hz would not safely repair it'}}else{return{value,steps,verified:false,stopReason:'DC offset has no safe parameter-only repair'}}if(JSON.stringify(next)===JSON.stringify(value))return{value,steps,verified:false,stopReason:'No further safe parameter change for '+problem};const nb=await renderSound(next);alive();const after=inspectBuffer(nb);steps.push({iteration:i,issue:problem,action,before,after,target});value=next;buffer=nb;before=after;if(ok(after))return{value,steps,verified:true,stopReason:'Inspector status is clean'}}return{value,steps,verified:ok(before),stopReason:ok(before)?'Inspector status is clean':'Iteration limit reached'}}

export function downloadOptimization(r:OptimizeResult,name:string){const json=JSON.stringify(r,(_k,v)=>typeof v==='number'&&!Number.isFinite(v)?null:v,2),u=URL.createObjectURL(new Blob([json],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=(name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'resona')+'.optimize.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
