import{audioBufferToWav}from'./audio';
export type Wave='sine'|'square'|'sawtooth'|'triangle';export type Step={note:number;on:boolean};export type Track={name:string;wave:Wave;gain:number;steps:Step[]};export type Song={name:string;bpm:number;bars:number;key:number;tracks:Track[]};
const n=[48,48,55,48,51,48,58,55,60,60,67,60,63,60,70,67];
export const defaultSong:Song={name:'Neon Loop',bpm:112,bars:2,key:0,tracks:[{name:'Bass',wave:'sawtooth',gain:.13,steps:n.map((v,i)=>({note:v,on:i%4===0}))},{name:'Pulse',wave:'square',gain:.055,steps:n.map((v,i)=>({note:v+12,on:i%2===0}))},{name:'Lead',wave:'triangle',gain:.08,steps:n.map((v,i)=>({note:v+24,on:[3,7,10,14].includes(i)}))}]};
const hz=(m:number)=>440*Math.pow(2,(m-69)/12),seconds=(s:Song)=>60/s.bpm/4*16*s.bars;
function schedule(ctx:BaseAudioContext,s:Song,dest:AudioNode,start:number){const step=60/s.bpm/4;for(let bar=0;bar<s.bars;bar++)s.tracks.forEach(t=>t.steps.forEach((x,i)=>{if(!x.on)return;const at=start+(bar*16+i)*step,o=ctx.createOscillator(),g=ctx.createGain();o.type=t.wave;o.frequency.value=hz(x.note+s.key);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(t.gain,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+step*.8);o.connect(g);g.connect(dest);o.start(at);o.stop(at+step*.85)}));return seconds(s)}
export function playSong(ctx:AudioContext,s:Song){return schedule(ctx,s,ctx.destination,ctx.currentTime)}
export async function renderSong(s:Song){const sr=48000,c=new OfflineAudioContext(2,Math.ceil(sr*seconds(s)),sr);schedule(c,s,c.destination,0);return c.startRendering()}
export async function exportSong(s:Song){const b=await renderSong(s),u=URL.createObjectURL(audioBufferToWav(b)),a=document.createElement('a');a.href=u;a.download=(s.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'resona-loop')+'.wav';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
