import{audioBufferToWav}from'./audio';
export type Wave='sine'|'square'|'sawtooth'|'triangle';export type Step={note:number;on:boolean};export type Track={name:string;wave:Wave;gain:number;steps:Step[]};export type Drum='kick'|'snare'|'hat';export type DrumTrack={name:string;kind:Drum;gain:number;steps:boolean[]};export type Song={version:1;seed:number;name:string;bpm:number;bars:number;key:number;tracks:Track[];drums:DrumTrack[]};
const n=[48,48,55,48,51,48,58,55,60,60,67,60,63,60,70,67],pat=(xs:number[])=>Array.from({length:16},(_,i)=>xs.includes(i));
export const defaultSong:Song={version:1,seed:777,name:'Neon Loop',bpm:112,bars:2,key:0,tracks:[{name:'Bass',wave:'sawtooth',gain:.13,steps:n.map((v,i)=>({note:v,on:i%4===0}))},{name:'Pulse',wave:'square',gain:.055,steps:n.map((v,i)=>({note:v+12,on:i%2===0}))},{name:'Lead',wave:'triangle',gain:.08,steps:n.map((v,i)=>({note:v+24,on:[3,7,10,14].includes(i)}))}],drums:[{name:'Kick',kind:'kick',gain:.5,steps:pat([0,4,8,12])},{name:'Snare',kind:'snare',gain:.2,steps:pat([4,12])},{name:'Hat',kind:'hat',gain:.08,steps:pat([0,2,4,6,8,10,12,14])}]};
const hz=(m:number)=>440*Math.pow(2,(m-69)/12),seconds=(s:Song)=>60/s.bpm/4*16*s.bars;function rng(seed:number){let a=seed|0;return()=>{a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296}}
function noise(ctx:BaseAudioContext,n:number,seed:number){const b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*n),ctx.sampleRate),d=b.getChannelData(0),r=rng(seed);for(let i=0;i<d.length;i++)d[i]=r()*2-1;return b}
function drum(ctx:BaseAudioContext,k:Drum,gain:number,dest:AudioNode,at:number,seed:number,sources:AudioScheduledSourceNode[]){if(k==='kick'){const o=ctx.createOscillator(),g=ctx.createGain();sources.push(o);o.frequency.setValueAtTime(150,at);o.frequency.exponentialRampToValueAtTime(42,at+.16);g.gain.setValueAtTime(gain,at);g.gain.exponentialRampToValueAtTime(.0001,at+.22);o.connect(g);g.connect(dest);o.start(at);o.stop(at+.23);return}const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();sources.push(src);src.buffer=noise(ctx,.22,seed);f.type='highpass';f.frequency.value=k==='hat'?6500:1200;g.gain.setValueAtTime(gain,at);g.gain.exponentialRampToValueAtTime(.0001,at+(k==='hat'?.055:.18));src.connect(f);f.connect(g);g.connect(dest);src.start(at);src.stop(at+(k==='hat'?.06:.19))}
function schedule(ctx:BaseAudioContext,s:Song,dest:AudioNode,start:number){const sources:AudioScheduledSourceNode[]=[],step=60/s.bpm/4;for(let bar=0;bar<s.bars;bar++){s.tracks.forEach(t=>t.steps.forEach((x,i)=>{if(!x.on)return;const at=start+(bar*16+i)*step,o=ctx.createOscillator(),g=ctx.createGain();sources.push(o);o.type=t.wave;o.frequency.value=hz(x.note+s.key);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(t.gain,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+step*.8);o.connect(g);g.connect(dest);o.start(at);o.stop(at+step*.85)}));s.drums.forEach((t,di)=>t.steps.forEach((on,i)=>on&&drum(ctx,t.kind,t.gain,dest,start+(bar*16+i)*step,(s.seed+bar*4099+di*257+i*17)>>>0,sources)))}return{duration:seconds(s),sources}}
export function playSong(ctx:AudioContext,s:Song){const bus=ctx.createGain();bus.connect(ctx.destination);const handle=schedule(ctx,s,bus,ctx.currentTime);let stopped=false;return{duration:handle.duration,stop:()=>{if(stopped)return;stopped=true;for(const source of handle.sources)try{source.stop()}catch{}try{bus.gain.cancelScheduledValues(ctx.currentTime);bus.gain.setValueAtTime(bus.gain.value,ctx.currentTime);bus.gain.linearRampToValueAtTime(0,ctx.currentTime+.015);setTimeout(()=>bus.disconnect(),30)}catch{bus.disconnect()}}}}export async function renderSong(s:Song){const sr=48000,c=new OfflineAudioContext(2,Math.ceil(sr*seconds(s)),sr);schedule(c,s,c.destination,0);return c.startRendering()}export async function exportSong(s:Song){const b=await renderSong(s),u=URL.createObjectURL(audioBufferToWav(b)),a=document.createElement('a');a.href=u;a.download=(s.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'resona-loop')+'.wav';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
